trigger:
- master
- dev

jobs:

- job: 'Test'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      addToPath: true
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest --cov=JavPy --ignore=JavPy/app/web
      codecov --token=0ee9ff43-ddb6-4f13-9ad3-12eebd6b7506
    displayName: 'test'
