name: JavPy Build Test

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: ${{ matrix.python-version }} @ ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 10.x

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.platform }}
      uses: actions/setup-python@v1.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Python ${{ matrix.python-version }} on ${{ matrix.platform }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: pytest --ignore=JavPy/app/web --cov=JavPy --cov-report=xml JavPy/tests/test_clients/

    - name: upload coverage
      if: job.name == '3.7 @ ubuntu-latest'
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
